services:
  gradio:
    build:
      context: gradio-project
      dockerfile: Dockerfile
    command: python3 gradio_app.py
    ports:
      - "7870:7860"
    tty: true
    volumes:
      - ./gradio-project:/app

  cefr:
    build: 
      context: cefr-predictor
      dockerfile: Dockerfile
    command: python3 cefr_app.py
    ports:
      - "7871:8080"
    tty: true
    volumes:
      - ./cefr-predictor:/app