services:
  gradio:
    build:
      context: gradio-project
      dockerfile: Dockerfile
    command: python3 gradio_app.py
    ports:
      - "7870:7860"
    tty: true
    volumes:
      - ./gradio-project:/app