services:
  gradio:
    build:
      context: gradio-project
      dockerfile: Dockerfile
    command: python3 gradio_app.py
    ports:
      - "7870:7860"
    tty: true
    volumes:
      - ./gradio-project:/app/gradio
      
  backend-project:
    env_file:
      - backend-project/.env
    build:
      context: backend-project
      dockerfile: Dockerfile
    volumes:
      - ./backend-project:/backend
      - media:/media
    command: fastapi dev --host 0.0.0.0 --port 8000 /backend/main.py
    ports:
      - "7871:8000"
    tty: true
    networks:
      - backend-network

  db:
    build:
      context: db-project
      dockerfile: Dockerfile
    container_name: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    env_file:
      - db-project/.env
    ports:
        - 7872:3306
    volumes:
        - db-store:/var/lib/mysql
        - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
        # ★ ローカルのscriptディレクトリにマウントします
        - ./db-project/init:/docker-entrypoint-initdb.d 
    tty: true
    networks:
      - backend-network
volumes:
  db-store:
  media:

networks:
  backend-network:
    driver: bridge